language: node_js
node_js: node
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  api_key:
    secure: JtYBFQLrWtUaQiy19Nikg3fcBVb7l/VLSv+QoZQ3OxANCS1AnAB62GtdeifYYp2u/3FPlkf9tnk4cX3TW5ASLC4JJoCu5v2AuZwRc5358IAoKK2QQ/wtUR2iUnBhL17OTSgEq0mYG3dM4q3Kk20jzRrGBsKERF2gTAONjlSHwon1Rm0ErEryo0FJeYAjcIV47WcmWUWicqvkStznnvUr++CG1soS87CFvIAA/D4/iM8WrOhx40VuE+lFin/PnvOH2gdwVkexaz3n6mgRb+fMhWSvVNbrOpSa/aRImqHcSzE6OCqEcq60S/c/OgdInZh7xyRJor6Iz/IAn+hodPjDOtQZPSpql1Q4huuXdkSgj1tZUqvd4pG1W/HD7OnFj5fEdVO2UIuPWNTK2BL2cCW1kEQxSc9IS+w7IZS59QNKEFw3LARb4HMYd88OJkM079ObYkw07ZKd/uZLm9f5tI3Z/fF1FZqecHB1U8NJ0N/BtnunIw74T4RbgtNZAGVcARf/fw2GZgt374D/pHl7mZhZ/b9r623+MvLX82woha4jYQopY9DSltFGMAx2b8HLldEl01LPop2hsDWv9F8uq4FWTG8TGvS3T/lHGnkbZe0UqhqRaYsJw/N/c+7dnLuQ5dCTpbhRVQu+C7UK1MSZdz/aKFypnd/KkD7DCsyodYgR218=
  app: quiet-beyond-44594
  on:
    repo: xxsenix/colloquy-client
