language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: pbkr6MVCctvEJXywkN3MyUpTz2hHuYkIWKwmnn7GcjwKXueaGnPmzNiwRU6JPq4a/tfEq1S/YohLhheZYC303qrdEKM/e67a7P5jphuc6louJY9o2Usl9qQyXUt73FFBOdYWkDDRSpsQrmQlXiSKs1S36bWkTmj5qjKlk3chRA6uXDU+B7Xfkk2JyicBHw4BMeVkZxXmP4LRvtQ2Mn6mkYoEHlJkNnD2sdXBpplWmrufe6GrtFPIBKe3psj5KT1zool3eB0klXvomgd/w/QLzXpaBA7W2JNqzu/rToqxRjy8jhS1UZVlzfuVGQTW2g8VOHQoHHUIplWBT8RimJ4T+xKOTs5z2i4/IpjZ2lYWaDBjjmKUn8wA62COcriMrusdnvZFKmpLFZY8KtqEnQD7HjBgV71a+MEAk+aJvtkH6ktxeT23msszteuOnRlmc2vq8Dvdulqyne6Vx6IgEiOieUvHTFoxAVTufBMD2YDyFNRst8Zm7mlTV3+NUG4CKP6ODBHjrWbVqD1kxBhs3h1snr8QoiprlqRDKyJmIoSKDACJIAL5AP5A1hE6A9icR95HrBkn+BM9+UniCuQJRVy86CHvY8brWLb2a0390dhHE0MZofaYPBAtCr/Z5C4tallmftgsPeKsm0Q53krCenfcjCzq95mdOmDsleHqzkIYI8M=
  app: quiet-beyond-44594
  on:
    repo: xxsenix/colloquy-client
